add:画像をアップロードしてカテゴリー別に表示させる
yanatoritakuma/GourmetApp-Next.js pull request #7
Opened 2021-07-31 05:05 UTC by yanatoritakuma

2021-08-03 01:47 UTC, fiftie requested changes
コメントしましたー！

2021-08-03 01:47 UTC, fiftie commented on components/Layout.jsx
> +  const menuRef = useRef(null);
もし使ってなかったら消しましょう

2021-08-03 01:47 UTC, fiftie commented on components/Layout.jsx
>    const [openHum, setOpenHum] = useState(false);
`Hum` ってなんです？？

2021-08-03 01:47 UTC, fiftie commented on pages/Registration.jsx
> +    setPhoto(imageUrl)
- セミコロンがない
- photoなのかimageなのかぶれてる
- photoではなくphotoUrlでは？

2021-08-03 01:47 UTC, fiftie commented on styles/global.css
>  .humMen {
humMenって口ずさむ男って意味に捉えちゃう

2021-08-15 09:49 UTC, fiftie requested changes
コメントしましたー

2021-08-15 09:49 UTC, fiftie commented on components/Layout.jsx
> +  };
書き方正しい？

2021-08-15 09:49 UTC, fiftie commented on components/Layout.jsx
> +    openHam && menuRef.current.focus();
`openHam` がtrueのときだけ実行したいなら、書き方を間違えてます

2021-08-15 09:49 UTC, fiftie commented on components/Layout.jsx
> +              src="/image/logo.JPG"
細かいですが、拡張子をわざわざ大文字にしなくていいです

2021-08-15 09:49 UTC, fiftie commented on components/Layout.jsx
> +              <a className="header__boxLink">Category</a>
hrefを使わないならaタグである必要はないでしょう

2021-08-15 09:49 UTC, fiftie commented on components/ModalStaet.jsx
> +  const checkLoginID = dispatch(loginIDStates(loginID));
`dispatch` の戻り値を使うのは良くないし、意味ないです
selectorで取得した値を使いましょう

2021-08-15 09:49 UTC, fiftie commented on components/ModalStaet.jsx
> +          {switchDelete()}
関数にしないでワンライナーで書いたほうが見やすそう

2021-08-15 09:49 UTC, fiftie commented on hooks/useAuth.jsx
> +import { useRouter } from 'next/router'
セミコロン

2021-08-15 09:49 UTC, fiftie commented on hooks/useAuth.jsx
> +    axios.get(`https://jsonplaceholder.typicode.com/users/${id}`).then((res) => {
axiosは古すぎるのでやめましょう笑
fetchがいいかなと

2021-08-15 09:49 UTC, fiftie commented on pages/Login.jsx
> +const  Login = () => {
変なスペース

2021-08-15 09:49 UTC, fiftie commented on pages/Login.jsx
> +  const disabled = true;
定数でtrueを定義する必要ない

2021-08-15 09:49 UTC, fiftie commented on pages/Login.jsx
> +import { loginIDStates } from "../provider/dishesSlice";
ここらへんせみころん

2021-08-17 02:39 UTC, fiftie requested changes
コメントしましたー
大きな問題はないのでTSに書き換えていいと思います

2021-08-17 02:39 UTC, fiftie commented on components/ModalStaet.jsx
> +          }
わざわざ関数にしなくてもワンライナーでかけると思います

2021-08-17 02:39 UTC, fiftie commented on package.json
> +    "axios": "^0.21.1",
使わないなら消しましょう

2021-08-17 02:39 UTC, fiftie commented on styles/global.scss
> +  left: -1000px;
一応確認ですが、ユーザが横に長いディスプレイを使っている場合でも問題ないですかね？？

2021-08-17 12:01 UTC, yanatoritakuma commented on styles/global.scss
> +  left: -1000px;
はい。
問題ないです。

2021-08-23 04:00 UTC, fiftie requested changes
おまたせしました、レビューしましたー
キリのいいところでマージしてもらえないと差分が多すぎてチェック大変なのでお願いします。

2021-08-23 04:00 UTC, fiftie commented on app/hooks.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
セミコロン無い
リンターやフォーマッターでチェックするといいかもですね
自動でつけるようにすることもできます

2021-08-23 04:00 UTC, fiftie commented on provider/dishesSlice.ts
> +  loginID: string[]
loginIDs

2021-08-23 04:00 UTC, fiftie commented on provider/dishesSlice.ts
> +    deleteCategory(state,action:PayloadAction<any>) {
`any` は使わない
絶対に禁止です。

2021-08-23 04:00 UTC, fiftie commented on provider/dishesSlice.ts
> +export default dishesSlice.reducer
せみころん

2021-08-23 04:00 UTC, fiftie commented on styles/global.scss
> +        padding: 0 .3em;
何故em?

2021-08-23 04:00 UTC, fiftie commented on tsconfig.json
> +    "target": "es5",
なぜes5?

2021-08-24 13:10 UTC, merged